### ISSUE TITLE
Do not support 7.0.11

### ISSUE THREAD

**Issue by kangtao10000** [igbinary/igbinary7#26] opened 2016-11-08 03:57 UTC
igbinary_unserialize_header: unsupported version: 1098019425

**Comment by TysonAndre** [comment] 2016-11-08 04:10
1. This repo is not maintained, clone https://github.com/igbinary/igbinary instead
2. This is a duplicate of https://github.com/igbinary/igbinary/issues/51

The string you passed it wasn't serialized with igbinary. The string passed to igbinary_unserialize was probably "Array", with that 4-byte suffix

```
php > echo "\x41\x72\x72\x61";
Arra
php > printf("0x%x\n", 1098019425);
0x41727261
```

**Closed as completed by TysonAndre** 2016-11-08 04:10 UTC
